---

- name: Sleep for 60 seconds and continue with play for the host to become available
  ansible.builtin.wait_for: timeout=60

- name: Add host to known_keys
  ansible.builtin.shell: ssh-keyscan -H {{ nat_ip_address }} >> ~/.ssh/known_hosts
