---
- name: reload alertmanager
  service:
    name: alertmanager
    state: reloaded

- name: restart alertmanager
  become: true
  systemd:
    daemon_reload: yes
    enabled: yes
    name: alertmanager
    state: restarted