# This file was autogenerated as a result of setting up a YC account

variable "yc_cloud_id" {
  type = string
  default = "b1gkltlcig08copnc8bc"
  description = "ID облака"
}

variable "yc_folder_id" {
  type = string
  default = "b1gjed8md31ldtt38dov"
  description = "ID каталога"
}

variable "yc_sa_account" {
  type = string
  default = "ajerk4goltnbscc54rko"
  description = "ID сервисного аккаунта"
}

variable "yc_sa_key_path" {
  type = string
  default = "/Users/ansakoy/Documents/Courses/netology/devnet-diploma/key.json"
  description = "Путь к ключу сервисного аккаунта"
}

variable "yc_zone_1a" {
  type = string
  default = "ru-central1-a"
  description = "Зона доступности A"
}

variable "yc_zone_1b" {
  type = string
  default = "ru-central1-b"
  description = "Зона доступности B"
}

